repository:
  name: versions-diff
  description: "Easier Blitz upgrades by clearly exposing changes from a version to another. :rocket:"
  homepage: https://react-native-community.github.io/upgrade-helper
  topics: blitz, upgrade, purge, versions-diff, versions-diff-purge, upgrade-helper

  has_wiki: false
